ybsuggestions/application/views.py
from flask import redirect, render_template, request, Blueprint
from ybsuggestions.models import Profile, Movie, Genre, ProfileSuggestion
from ybsuggestions.forms import ProfileForm
from ybsuggestions import db


def get_defaults():
    if 'profile_id' in request.cookies:
        profile_id = int(request.cookies.get('profile_id'))
        current_profile = Profile.query.get(profile_id)
    else:
        current_profile = Profile.query.order_by(Profile.id.asc()).first()

    if not current_profile:
        current_profile = Profile(name='Default Profile', min_rating=0.0)
        db.session.add(current_profile)
        db.session.commit()
        db.session.flush()

    profiles = Profile.query.all()
    if not profiles:
        profiles = None

    defaults = {
        'profiles': profiles,
        'current_profile': current_profile
    }

    return defaults


application_blueprint = Blueprint('application', __name__, template_folder='templates')


@application_blueprint.route('/')
@application_blueprint.route('/index')
def index():
    context = get_defaults()

    if context['current_profile'].blacklist:
        movies = Movie.query.filter(
            ~Movie.genres.any(
                Genre.id.in_(
                    [g.id for g in context['current_profile'].blacklist])),
            Movie.rating >= context['current_profile'].min_rating
        ).order_by(Movie.date.desc())
    else:
        movies = Movie.query.filter(
            Movie.rating >= context['current_profile'].min_rating
        ).order_by(Movie.date.desc())

    context.update({
        'movies': movies,
        'title': 'Home',
        'dismissed_movies': [s.movie_id for s in context['current_profile'].rated_suggestions if not s.was_liked],
        'liked_movies': [s.movie_id for s in context['current_profile'].rated_suggestions if s.was_liked]
    })

    return render_template("index.html", **context)


@application_blueprint.route('/profile/', methods=['GET', 'POST'])
@application_blueprint.route('/profile/<int:profile_id>/', methods=['GET', 'POST'])
@application_blueprint.route('/profile/<operation>/', methods=['GET'])
@application_blueprint.route('/profile/<operation>/<int:profile_id>', methods=['GET'])
def profile(profile_id='', operation=''):
    if request.method == 'POST':
        return post_profile(profile_id=profile_id)
    else:
        return get_profile(profile_id=profile_id, operation=operation)


def get_profile(profile_id='', operation=''):
    context = get_defaults()
    path = '/profile/'
    form = ProfileForm()

    if operation == 'new':

        context.update({
            'path': path,
            'form': form,
            'action': path
        })

        return render_template("profile_detail.html", **context)

    if operation == 'delete':
        obj = Profile.query.get(profile_id)
        db.session.delete(obj)
        db.session.commit()
        return redirect(path)

    if profile_id:
        profile = Profile.query.get(profile_id)

        form = ProfileForm(obj=profile)

        action = request.path

        dismissed_suggestions = [s for s in profile.rated_suggestions if not s.was_liked]

        dismissed = []
        if dismissed_suggestions:
            for suggestion in dismissed_suggestions:
                dismissed.append((suggestion.id, Movie.query.get(suggestion.movie_id).name))

        context.update({
            'path': path,
            'form': form,
            'action': action,
            'dismissed': dismissed
        })

        return render_template("profile_detail.html", **context)

    profiles = Profile.query.all()

    context.update({
        'path': path,
        'obj': profiles,
    })

    return render_template("profile_list.html", **context)


def post_profile(profile_id=''):
    path = '/profile/'

    if profile_id:
        profile = Profile.query.get(profile_id)
    else:
        profile = Profile()

    form = ProfileForm(request.form)
    form.populate_obj(profile)

    db.session.add(profile)
    db.session.commit()

    return redirect(path)


@application_blueprint.route('/profile_suggestion/<int:profile_id>/<operation>/<int:ps_id>', methods=['GET'])
def profile_suggestion(profile_id='', ps_id='', operation=''):
    path = '/profile/%d' % profile_id

    if operation == 'delete':
        ps = ProfileSuggestion.query.get(ps_id)

        if ps:
            db.session.delete(ps)
            db.session.commit()

    return redirect(path)

ybsuggestions/application/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% if title %}
    <title>{{ title }} - MovieSuggestions</title>
    {% else %}
    <title>MovieSuggestions</title>
    {% endif %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/foundation.min.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/foundation-icons.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" />
</head>
<body>
    <div class="off-canvas-wrapper">
        <div class="off-canvas-wrapper-inner" data-off-canvas-wrapper>
            <div class="off-canvas position-left reveal-for-large" id="profile-info" data-off-canvas>
                <div class="row column">
                    <br/>
                    {% if profiles %}
                    <label>Profile: </label>
                    <select id="profile_select">
                        {% for profile in profiles %}
                        <option value="{{ profile.id }}" {% if profile==current_profile %} selected{% endif %}>{{ profile.name }}</option>
                        {% endfor %}
                    </select>
                    <a href="{{ url_for('application.profile') }}{{current_profile.id}}" class="button edit_profile">Edit</a>
                    {% endif %}
                    <a href="#" class="button add_profile">Add new</a>
                </div>
                <div class="row column">
                    <ul class="vertical menu">
                      <li><a href="{{ url_for('application.index') }}">Home</a></li>
                      <li><a href="{{ url_for('application.profile') }}">Profiles</a></li>
                    </ul>
                </div>
            </div>

            <div class="off-canvas-content" data-off-canvas-content>
                <div class="title-bar hide-for-large">
                    <div class="title-bar-left">
                    <button class="menu-icon" type="button" data-open="profile-info"></button>
                    <span class="title-bar-title">{{ current_profile.name }}</span>
                    </div>
                </div>

                <div class="callout primary">
                {% block primary %}{% endblock %}
                </div>

                {% block content %}{% endblock %}

            </div>
        </div>
    </div>

    <script src="{{ url_for('static', filename='js/jquery-2.1.4.min.js') }}"></script>
    <script src="{{ url_for('static', filename='js/foundation.js') }}"></script>
    <script>
      $(document).foundation();
    </script>
    <script src="{{ url_for('static', filename='js/js.cookie.js') }}"></script>

    <script src="{{ url_for('static', filename='js/jquery.twbsPagination.js') }}"></script>
    <script src="{{ url_for('static', filename='js/scripts.js') }}"></script>
    <script>
        var profile_url = '{{ url_for('application.profile') }}';
        var dismiss_suggestion_url = '{{ url_for('apis.post_dismiss_suggestion') }}';
        var good_suggestion_url = '{{ url_for('apis.post_good_suggestion') }}';
    </script>
</body>
</html>

ybsuggestions/application/templates/index.html
{% extends "base.html" %}

{% block primary %}
    <div class="row column">
    <h3>Hello! We have some fresh movies for you!</h3>
    </div>
{% endblock %}

{% block content %}
    <div class="suggestions row small-up-2 medium-up-3 large-up-4">
    {% for movie in movies %}
        {% if movie.id not in dismissed_movies %}
        <div id="movie-{{ movie.id }}" class="movie-item column">
            <table class="unstriped">
                <tr>
                    <td class="title" colspan="2">{{movie.name}}</td>
                </tr>
                <tr>
                   <td class="thumb" rowspan="2" width="94">
                       <img class="thumbnail" src="{% if movie.cover %}{{movie.cover}}{% else %}http://placehold.it/94x140{% endif %}">
                   </td>
                    <td class="genres">
                    {% for genre in movie.genres %}
                        <span class="radius{% if genre not in current_profile.whitelist %} secondary{% endif %} label">{{genre.name}}</span>
                    {% endfor %}
                    </td>
                </tr>
                <tr>
                    <td class="rating">IMDb: {% if movie.rating > 0 %}{{movie.rating}}{% else %}N/A{% endif %}</td>
                </tr>
                <tr>
                    <td class="rate" colspan="2">
                        <a data-movie-id="{{movie.id}}" class="rate_base rate_down">
                            <i class="fi-dislike medium"></i>
                        </a>
                        <a data-movie-id="{{movie.id}}" class="rate_base{% if movie.id in liked_movies %} rated_up{% else %} rate_up{% endif %}">
                            <i class="fi-like medium"></i>
                        </a>
                    </td>
                </tr>
            </table>
        </div>
        {% endif %}
    {% endfor %}
    </div>
    <div class="suggestions-pagination row small-up-2 medium-up-3 large-up-4">
        <ul class="pagination" id="pagination" role="navigation" aria-label="Pagination"></ul>
    </div>
{% endblock %}

ybsuggestions/application/templates/movie_list.html
{% extends "base.html" %}

{% block content %}
	<div class="object-list row">
        <div class="large-12">
            <table>
                <tr>
                    <th style="width: 20px">#</th>
                    <th>Name</th>
                    <th>IMDb</th>
                    <th>Updated</th>
                    <th style="width: 50px">Actions</th>
                </tr>
                {% for item in obj %}
                    <tr>
                        <td>{{ item.id }}</td>
                        <td><a href="{{ url_for('application.movie') }}{{ item.id }}" title="{{ item.name }}">{{ item.name }}</a></td>
                        <td>{{ item.rating }}</td>
                        <td>{{ item.date }}</td>
                        <td><a class="pure-button pure-button-primary button blue" href="{{path + item.id|string}}">Edit</a></td>
                    </tr>
                {% endfor %}
            </table>
        </div>
	</div>

{% endblock %}

ybsuggestions/application/templates/object_detail.html
{% extends "base.html" %}

{% block content %}
    <form action="{{ action }}" method="post">
	<div class="row">
        {% for field in form %}
        <div class="large-12 columns">
        {{ field.name }}
        {{ field }}
        </div>
        {% endfor %}
        <div class="large-12 columns">
            <input class="button" type="submit" value="Send" />
        </div>
	</div>
    </form>
{% endblock %}

ybsuggestions/application/templates/profile_detail.html
{% extends "base.html" %}

{% block primary %}
    <div class="row column">
    <h3>Manage profile {% if form.name %}{{ form.name.value }}{% endif %}</h3>
    </div>
{% endblock %}

{% block content %}
    <form action="{{ action }}" method="post">
    {{ form.hidden_tag() }}
	<div class="row">
        <div class="large-12 columns">
            <label>Name:</label>
            {{ form.name }}
        </div>
        <div class="large-12 columns">
            <label>Minimal rating:</label>
            {{ form.min_rating }}
        </div>
        <div class="large-12 columns select_genres">
            <label>Whitelist:</label>
            {{ form.whitelist }}
        </div>
        <div class="large-12 columns select_genres">
            <label>Blacklist:</label>
            {{ form.blacklist }}
        </div>
        <div class="large-12 columns">
            <input class="button" type="submit" value="Send" />
        </div>
	</div>
    </form>
    <div class="row">
        <div class="large-12">
            <table style="width: 100%">
                <caption><h5>Dismissed suggestions</h5></caption>
                <tr>
                    <th style="width: 20px">#</th>
                    <th>Movie id</th>
                    <th style="width: 100px">Actions</th>
                </tr>
                {% for suggestion in dismissed %}
                    <tr>
                        <td>{{ suggestion.0 }}</td>
                        <td>{{ suggestion.1 }}</td>
                        <td>
                            <a class="button red" href="{{ url_for('application.profile_suggestion', operation='delete', profile_id=current_profile.id, ps_id=suggestion.0) }}">Delete</a>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
{% endblock %}

ybsuggestions/application/templates/profile_list.html
{% extends "base.html" %}

{% block content %}
	<div class="object-list row">
        <div class="large-12">
            <table>
                <tr>
                    <th style="width: 20px">#</th>
                    <th>Name</th>
                    <th style="width: 200px">Actions</th>
                </tr>
                {% for item in obj %}
                    <tr>
                        <td>{{ item.id }}</td>
                        <td><a href="{{ url_for('application.profile') }}{{ item.id }}" title="{{ item.name }}">{{ item.name }}</a></td>
                        <td>
                            <a class="button blue" href="{{path + item.id|string}}">Edit</a>
                            <a class="button red" href="{{path + 'delete/' + item.id|string}}">Delete</a>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
	</div>

{% endblock %}